name: check

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  check:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install uv
        uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6.8.0
        with:
          version-file: .tool-versions
          enable-cache: true
          save-cache: ${{ github.ref == 'refs/heads/main' }}

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        id: install
        run: |
          uv sync --dev --frozen

      - name: lint
        run: |
          uv run ruff check --output-format github .

      - name: check format
        run: |
          uv run ruff format --check .
